<?php

declare(strict_types=1);

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\Collectives\Service;

/**
 * Renders static HTML pages for the Collectives static site export.
 */
class StaticSiteRenderer {
	/**
	 * @param list<array{id: int, title: string, summary: string}> $pages
	 */
	public function renderIndex(string $outDir, array $pages, string $title, string $userId): void {
		$cards = '';
		if ($pages === []) {
			$cards = '<article class="card"><p>No pages were selected for this static site.</p></article>';
		} else {
			foreach ($pages as $page) {
				$href = 'page-' . $page['id'] . '/';
				$cards .= '<article class="card">'
					. '<h2><a href="' . $this->e($href) . '">' . $this->e($page['title']) . '</a></h2>';
				if ($page['summary'] !== '') {
					$cards .= '<p>' . $this->e($page['summary']) . '</p>';
				}
				$cards .= '</article>';
			}
		}

		$main = '<div class="cards">' . $cards . '</div>';
		$html = $this->wrapLayout(
			$title,
			$title,
			'A static site generated from Nextcloud Collectives',
			$main,
			$userId,
		);
		file_put_contents($outDir . '/index.html', $html);
	}

	/**
	 * @param array{id: int, title: string, html: string} $page
	 */
	public function renderPage(string $outDir, array $page, string $siteTitle, string $userId): void {
		$dir = $outDir . '/page-' . $page['id'];
		@mkdir($dir, 0o700, true);

		$main = '<article class="page">'
			. '<a class="back" href="../">← Back to overview</a>'
			. '<div class="content">' . $page['html'] . '</div>'
			. '</article>';

		$html = $this->wrapLayout($page['title'], $siteTitle, $page['title'], $main, $userId);
		file_put_contents($dir . '/index.html', $html);
	}

	private function wrapLayout(string $documentTitle, string $siteTitle, string $subtitle, string $main, string $userId): string {
		$title = $this->e($documentTitle);
		$heroTitle = $this->e($siteTitle);
		$subtitleEscaped = $this->e($subtitle);
		$user = $this->e($userId !== '' ? $userId : 'Collectives');
		$timestamp = gmdate('Y-m-d H:i:s');

		return <<<HTML
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="generator" content="Nextcloud Collectives">
		<title>{$title}</title>
		<style>
			:root { color-scheme: light dark; }
			* { box-sizing: border-box; }
			body {
				margin: 0;
				font-family: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
				line-height: 1.6;
				color: #1a1a1a;
				background: #f5f6f8;
			}
			.hero {
				background: linear-gradient(135deg, #0082c9, #00b0ff);
				color: #fff;
				padding: 3rem 1.5rem 2.5rem;
				text-align: center;
			}
			.hero h1 { margin: 0 0 .5rem; font-size: clamp(1.8rem, 5vw, 3rem); }
			.hero p { margin: 0; opacity: .9; }
			main { max-width: 820px; margin: -1.5rem auto 3rem; padding: 0 1.5rem; }
			.cards { display: grid; gap: 1rem; }
			.card {
				background: #fff;
				border-radius: 12px;
				padding: 1.25rem 1.5rem;
				box-shadow: 0 4px 16px rgba(0,0,0,.06);
			}
			.card h2 { margin: 0 0 .25rem; font-size: 1.15rem; }
			.card h2 a { color: inherit; text-decoration: none; }
			.card h2 a:hover { text-decoration: underline; }
			.card p { margin: 0; color: #666; }
			.page {
				background: #fff;
				border-radius: 12px;
				padding: 1.5rem 2rem;
				box-shadow: 0 4px 16px rgba(0,0,0,.06);
			}
			.page .back { display: inline-block; margin-bottom: 1rem; color: #0082c9; text-decoration: none; }
			.page .content :first-child { margin-top: 0; }
			.page img { max-width: 100%; }
			.page pre { background: #f0f1f3; padding: 1rem; border-radius: 8px; overflow: auto; }
			.page table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
			.page th, .page td { border: 1px solid #d0d3d8; padding: .5rem .75rem; vertical-align: top; }
			.page th { background: #f0f1f3; font-weight: 600; }
			.page tr:nth-child(even) td { background: #fafbfc; }
			.page table p:first-child { margin-top: 0; }
			.page table p:last-child { margin-bottom: 0; }
			footer {
				text-align: center;
				padding: 2rem 1.5rem;
				color: #777;
				font-size: .85rem;
			}
			@media (prefers-color-scheme: dark) {
				body { background: #181818; color: #eee; }
				.card, .page { background: #242424; box-shadow: none; }
				.card p { color: #aaa; }
				.page pre { background: #1a1a1a; }
				.page th { background: #1a1a1a; }
				.page th, .page td { border-color: #3a3a3a; }
				.page tr:nth-child(even) td { background: #1e1e1e; }
			}
		</style>
	</head>
	<body>
		<header class="hero">
			<h1>⭐ {$heroTitle}</h1>
			<p>{$subtitleEscaped}</p>
		</header>
		<main>
			{$main}
		</main>
		<footer>
			Generated by {$user} · {$timestamp} UTC
		</footer>
	</body>
</html>
HTML;
	}

	private function e(string $value): string {
		return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
	}
}
